### PR TITLE
Update to 1.1.3

### PR DESCRIPTION
**Pull request by dhirschfeld**
Just playing around to see why the tests aren't being discovered

### CODE REVIEW

**Comment by msarahan** [comment]
It's because of the manifest.in. the meta.yaml needs test/source_files.

This seems to be platform specific for reasons I don't understand.

**Comment by dhirschfeld** [comment]
Looks like it will also need the `concurrent.futures` backport on py27 - but I'm sure you've already seen...

**Comment by msarahan** [comment]
Rebase on master

**Comment by dhirschfeld** [comment]
As a Windows user I was just curious why the tests weren't being picked up on Windows so thanks for the info - it might come in handy if I ever come across something similar...

**Pull request closed without merging**
