### PR TITLE
conda-package-handling v1.9.0 + add jezdez as maintainer.

### PR DESCRIPTION
**Pull request by jezdez**
Refs https://github.com/conda-forge/conda-package-handling-feedstock/pull/64#issuecomment-1245689399.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jezdez** [comment]
@conda-forge-admin, please rerender

**Review by dbast — APPROVED** [review]

**Comment by msarahan** [comment]
Might be better to not rerender for changes like this, just to simplify review. You could also skip ci.

**Comment by dbast** [comment]
@jezdez either bump the build number as rerender maybe leads to uploads or revert the rerender and add skip ci according to https://conda-forge.org/docs/maintainer/infrastructure.html#skipping-ci-builds

**Comment by dbast** [comment]
@jezdez You can also merge the other update PR branch into yours here and finish everything here.

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@jezdez merged https://github.com/conda-forge/conda-package-handling-feedstock/pull/64 into this PR.

**Comment by jezdez** [comment]
> Might be better to not rerender for changes like this, just to simplify review. You could also skip ci.

I was looking to have the `CODEOWNERS` file be up-to-date, which I was told in the past should be updated via the rerender and not manually. I split this from #64 to respond to Matt's comment.

> @jezdez merged https://github.com/conda-forge/conda-package-handling-feedstock/pull/64 into this PR.

@dbast This wasn't what I intended to do with this, but oh well.

**Comment by dbast** [comment]
@jezdez CODEOWNERS files was updated via rerender... not manually :)

**Comment by jezdez** [comment]
I talked with @dbast a little more and understand the workflow better, thanks for the help, y'all!

**Comment by jezdez** [comment]
This was fixed by deleting a branch in the conda-package-handling repo with an emoji in the name. Apparently, versioneer can't handle that when trying to figure out the version (on Windows).

**Comment by msarahan** [comment]
Please tell me it was a poop emoji. Always crapping things up.

**Comment by jezdez** [comment]
It was named "rever-1.9.0-2️⃣" 😬

**Comment by jezdez** [comment]
*shakes fist at sky*

**Review by dbast — APPROVED** [review]

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
